KEYBOARD_SHORTCUTS:
- button: pushButton_ToggleFill
  callback: toggleFillButton
  shortcut: f
- button: pushButton_ToggleVisibility
  callback: onPushButton_ToggleVisibility
  shortcut: v
- button: pushButton_undo
  callback: onPushButton_undo
  shortcut: z
- button: SaveSegmentationButton
  callback: onSaveSegmentationButton
  shortcut: s
- button: pushButton_Smooth
  callback: onPushButton_Smooth
  shortcut: l
- button: pushButton_Small_holes
  callback: onPushButton_Small_holes
  shortcut: o
- button: pushButton_Interpolate
  callback: onPushButton_Interpolate
  shortcut: i
- button: SaveClassificationButton
  callback: onSaveClassificationButton
  shortcut: c
checkboxes:
  aaaaa: Aaaaa
  ttt: Ttt
comboboxes:
  v01: {}
  v02:
    asdasd:
      '222': '122'
  v03:
    jean: &id001
      a: a
      bb: bb
      ccc: ccc
    roberto: &id002
      '1': '1'
      '22': '22'
      '333': '333'
      '4444': '4444'
  v04:
    jean: *id001
    roberto: *id002
    yoyo:
      '22': '22'
      '33': '33'
  v05:
    jean: *id001
    maxime:
      t: t
      u: u
      y: y
    roberto: *id002
  v06: {}
  v07:
    jean: *id001
    roberto: *id002
    yoyo:
      '22': '22'
      '33': '33'
  v08:
    jean:
      a: a
      bb: bb
      ccc: ccc
    roberto:
      '1': '1'
      '22': '22'
      '333': '333'
      '4444': '4444'
  v09:
    maxima:
      auto: auto
      b: b
    roberto:
      '1': '1'
      '22': '22'
      '333': '333'
      '4444': '4444'
ct_window_level: 45
ct_window_width: 85
default_segmentation_directory: ''
default_volume_directory: ''
enable_debug: true
freetextboxes:
  aasdas: Aasdas
  zimbabwe: Zimbabwe
impose_bids_format: false
input_filetype: '*.nii.gz'
interpolate_value: 0
is_classification_requested: true
is_display_timer_requested: false
is_keyboard_shortcuts_requested: true
is_mouse_shortcuts_requested: true
is_segmentation_requested: true
is_semi_automatic_phe_tool_requested: true
keep_working_list: false
labels:
- color_b: 10
  color_g: 10
  color_r: 255
  lower_bound_HU: 30
  name: ICH
  upper_bound_HU: 90
  value: 1
- color_b: 70
  color_g: 230
  color_r: 230
  lower_bound_HU: 30
  name: IVH
  upper_bound_HU: 90
  value: 2
modality: MRI
remaining_list_filename: remaining_list.yaml
require_empty: false
slice_view_color: Yellow
working_list_filename: working_list.yaml
